### ISSUE TITLE
Magnify tool freezes on multiple viewports

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1518]
### Describe the Bug

After using Magnify tool on multiple viewports and selecting another tool, the Magnify tool remains being displayed on the second and third viewports while the user is interacting with another tool.

![bug-magnify](https://user-images.githubusercontent.com/13245529/76572619-53fbb480-6499-11ea-9bbb-4c55202065c0.gif)

### Steps to Reproduce

1. Navigate to any study
2. Select Layout with 3 viewports
3. Select Magnify tool
4. Interact with viewport 1 and 2
5. Select another tool (i.e. Zoom, Pan)
6. Interact with each viewport 
7. Verify that Magnify rectangle shows up in viewport 2 and 3, even if user didn't use the Magnify tool in viewport 3 before

### Actual Result

1. When user selects a different tool, Magnify rectangle still showing up in viewport 2 and 3, even if user didn't use the Magnify tool in viewport 3 before

### Expected Result

1. User should be able to interact on the viewports with only the selected tool
2. Once user selects a different tool, the Magnify should be totally disabled

**Comment by dannyrb** [comment]
See community report in cornerstone-tools: https://github.com/cornerstonejs/cornerstoneTools/issues/1172

**Comment by JamesAPetts** [comment]
Believed this was fixed in https://github.com/cornerstonejs/cornerstoneTools/pull/1271.

**Comment by take5v** [comment]
Still reproduced @JamesAPetts @dannyrb.

![OHIF-Viewer-Google-Chrome-9-14-2](https://user-images.githubusercontent.com/1794068/93093599-8a64f700-f6a9-11ea-8271-db38f96217bb.gif)
