### ISSUE TITLE
With config.showStudyList : false -> Still showing hyperlink to StudyList on Not Found Component

### ISSUE THREAD

**Issue by Pela2silveira** [OHIF/Viewers#2130]
### Describe the Bug

If StudyList is disabled on configuration, and reach a non existent page, is still possible to go to StudyList, bceause hyperlink is present on Not Found Component

### What steps can we follow to reproduce the bug?

1. Set studylist to false in app-config.js
2. go to root url or to ohif/viewer url or to ohif/viewer/xxx , where xxx does not exist
3. click in "go to study list"

```js
Please use code blocks to show formatted errors or code snippets
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by swederik** [comment]
Looks like this is fixed in #2131 - Thanks for the report!

**Comment by mokbelt** [comment]
Dears,
This issue is still persisting... evening if **showStudyList: false**
(tested for the built version 3.3.0)
Any update how to solve it?

**Comment by elamathis18** [comment]
Hi, this error is still persisting in v3. Is there any workaround for this?
Thank you.
