### ISSUE TITLE
windowWidth.toFixed is not a function in viewerMain  [failed to load image]

### ISSUE THREAD

**Issue by brikjr** [OHIF/Viewers#2297]
i have some issues of app in my local host
**TypeError: windowWidth.toFixed is not a function**
and am not changed anything of code just upgrade node.js
![enter image description here](https://i.ibb.co/JFJ0m5p/Screenshot-297.png)

**Comment by alexiusll** [comment]
I have the same question

**Comment by msibal6** [comment]
I have the same problem. Did y'all get this problem by running `yarn run dev`? I worked around it by giving APP_CONFIG some value other than default.j, but I would also like some explanation on what is happening here.

**Comment by donghakang** [comment]
Did anyone find the solution or explanation for this?

**Comment by donghakang** [comment]
According to issue #2138 there is a work around.

I did what @gccgomes and @bianyueyan suggested. I am pretty sure it is not a fix but it is a workaround for CT images

**Comment by brikjr** [comment]
> I have the same problem. Did y'all get this problem by running `yarn run dev`? I worked around it by giving APP_CONFIG some value other than default.j, but I would also like some explanation on what is happening here.

i think the problem come from upgrading some functions on cornerstone library , problem show in CT ,  CT/PT images

**Comment by donghakang** [comment]
> > I have the same problem. Did y'all get this problem by running `yarn run dev`? I worked around it by giving APP_CONFIG some value other than default.j, but I would also like some explanation on what is happening here.
> 
> i think the problem come from upgrading some functions on cornerstone library , problem show in CT , CT/PT images

How about other image files like DICOM? Did you get them to work?

**Comment by brikjr** [comment]
just SM images work 
after changing `var wwwc = "W: ".concat(windowWidth.toFixed(0), " L: ").concat(windowCenter.toFixed(0));
into
var wwwc = "W: ".concat(Number(windowWidth).toFixed(0), " L: ").concat(Number(windowCenter).toFixed(0));var wwwc = "W: ".concat(windowWidth.toFixed(0), " L: ").concat(windowCenter.toFixed(0));
into
var wwwc = "W: ".concat(Number(windowWidth).toFixed(0), " L: ").concat(Number(windowCenter).toFixed(0));`

in the ./node_modules/react-cornerstone-viewport/dist/index.umd.js.

**Comment by brikjr** [comment]
> > > I have the same problem. Did y'all get this problem by running `yarn run dev`? I worked around it by giving APP_CONFIG some value other than default.j, but I would also like some explanation on what is happening here.
> > 
> > 
> > i think the problem come from upgrading some functions on cornerstone library , problem show in CT , CT/PT images
> 
> How about other image files like DICOM? Did you get them to work?

just SM images work after refactor code in node-modules according to [issue](https://github.com/OHIF/Viewers/issues/2138#issuecomment-771515850)

**Comment by igoroctaviano** [comment]
@swederik modifying react-cornerstone-viewport to consider both number / strings resolves the issue: https://github.com/cornerstonejs/react-cornerstone-viewport/pull/115

**Comment by brikjr** [comment]
> @swederik modifying react-cornerstone-viewport to consider both number / strings resolves the issue: [cornerstonejs/react-cornerstone-viewport#115](https://github.com/cornerstonejs/react-cornerstone-viewport/pull/115)

i wanna to show , this bug come after last commit team have made in in last version of ohif , i solve it when i reuse older version of ohif and modifying react-cornerstone-viewport to consider both number / strings  it solved but in last version this solution not working

**Comment by igoroctaviano** [comment]
> > @swederik modifying react-cornerstone-viewport to consider both number / strings resolves the issue: [cornerstonejs/react-cornerstone-viewport#115](https://github.com/cornerstonejs/react-cornerstone-viewport/pull/115)
> 
> i wanna to show , this bug come after last commit team have made in in last version of ohif , i solve it when i reuse older version of ohif and modifying react-cornerstone-viewport to consider both number / strings it solved but in last version this solution not working

Can you show which commit introduced the bug?

**Comment by brikjr** [comment]
> > > @swederik modifying react-cornerstone-viewport to consider both number / strings resolves the issue: [cornerstonejs/react-cornerstone-viewport#115](https://github.com/cornerstonejs/react-cornerstone-viewport/pull/115)
> > 
> > 
> > i wanna to show , this bug come after last commit team have made in in last version of ohif , i solve it when i reuse older version of ohif and modifying react-cornerstone-viewport to consider both number / strings it solved but in last version this solution not working
> 
> @brikjr Can you show which commit introduced the bug?

i don't know exactly which commit , but it's not working in version of 9 mar

**Comment by zhengxiuming** [comment]
I have the same question

**Comment by igoroctaviano** [comment]
I’ll open a PR today to bump react-cornerstone-viewport version in OHIF, this should solve the problem for now. Later I’ll open another that fix the issue in the OHIF metadata level.

**Comment by bnbn860904** [comment]
I downloaded the latest version of OHIF Viewer, and I still have the same problem in 2D MPR
If you can reply to me, I will thank you very much.[
![68](https://user-images.githubusercontent.com/76800812/111309142-846ec380-8696-11eb-99fb-8fb2cad895f7.png)
](url)

**Comment by igoroctaviano** [comment]
> I downloaded the latest version of OHIF Viewer, and I still have the same problem in 2D MPR
> If you can reply to me, I will thank you very much.[ ![68](https://user-images.githubusercontent.com/76800812/111309142-846ec380-8696-11eb-99fb-8fb2cad895f7.png) ](url)

Looks like this is not a toFixed issue. It could be related but it's a different error in a different OHIF extension that needs investigation, can you create the issue for it with this screenshot?

**Comment by bnbn860904** [comment]
OK , thank you very much.

**Comment by igoroctaviano** [comment]
Fixed in the latest version!
