### ISSUE TITLE
[Bug] VOI inverted status after updating SUV parameters

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#3485]
### Describe the Bug

Hi all,

A small bug visible in the demo server,

When going in the TMTV mode and changing a SUV parameter and hit the "reload data" button, the SUV parameter and recomputed which is normal but the Inverted status of the LUT is lost (see capture)

![image](https://github.com/OHIF/Viewers/assets/25229822/e2b387f9-ce5a-4dbd-a1c6-51aaed6a8004)

After double click on a viewport to make it full screen it goes back to the required inverted status

![image](https://github.com/OHIF/Viewers/assets/25229822/29a65ff0-f0d7-4a58-a046-b38f7d0e4127)

### Steps to Reproduce

1. Go to TMTV mode
2. change patient weight
3. Hit Reload data

### The current behavior

Voi inverted is lost, image has a black background for PT viewport

### The expected behavior

PET viewport shall perserve their inverted status when updated SUV volume being rendered (in our case white background)

### OS

Window and Linux

### Node version

18

### Browser

Chrome latest version

**Comment by sedghi** [comment]
This is most likely fixed in the recent pushes by me.

**Comment by jbocce** [comment]
I verified on https://viewer-dev.ohif.org/ and a local sandbox that this is still an issue. FYI @sedghi.

**Comment by sedghi** [comment]
I see, then it is another problem

**Comment by salimkanoun** [comment]
Sounds solved
